# Generated by Django 5.2.8 on 2025-11-21 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_materia', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Inscrito')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_estudiantes', to='core.materia', verbose_name='Materia Inscrita')),
            ],
            options={
                'verbose_name': 'Inscripción a Materia',
                'verbose_name_plural': 'Inscripciones a Materias',
                'ordering': ['materia', 'estudiante'],
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
